# Spring properties
spring:
  application:
    name: mongoDB-Service  # Identify this application
  freemarker:
    enabled: false     # Ignore Eureka dashboard FreeMarker templates

# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access
#  1. Define URL of registration server (defaultZone)
#  2. Reduce lease-renewal time so processes register more quickly
eureka:
  instance:
     leaseRenewalIntervalInSeconds: 30   # DO NOT DO THIS IN PRODUCTION
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port
